package com.api;

import com.TestContext.ScenarioContext;
import com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter;

import genericFunctions.FieldNames;
import genericFunctions.ReusableMethods;

public class APIPayLoad {
	
	private String customerName;
	
	public String customerName(ScenarioContext scenarioContext) {
		customerName = ReusableMethods.generateRandomValues("alphabets", 5);
		ExtentCucumberAdapter.addTestStepLog("FirstName : " + customerName);
		scenarioContext.addTestData(FieldNames.CustomerName.toString(), customerName);
		System.out.println(customerName);
		return customerName;
	}
	
	public String post_PrivateBody(ScenarioContext scenarioContext) {

		String body = "{\n"
				+ "    \"id\": null,\n"
				+ "    \"tenantId\": 5,\n"
				+ "    \"customerName\": \""+customerName(scenarioContext)+"\",\n"
				+ "    \"riskRatingId\": 1998,\n"
				+ "    \"locale\": \"en\",\n"
				+ "    \"customerRelatedPartyMappingDTOList\": [\n"
				+ "        {\n"
				+ "            \"relatedPartyFieldDocumentMappingDTOList\": [\n"
				+ "                {\n"
				+ "                    \"id\": null,\n"
				+ "                    \"relatedPartyId\": 1810,\n"
				+ "                    \"designationId\": null,\n"
				+ "                    \"orgTypeId\": 162,\n"
				+ "                    \"coiNationalityId\": 110,\n"
				+ "                    \"name\": \""+customerName(scenarioContext)+"\",\n"
				+ "                    \"email\": \"n@gmail.com\",\n"
				+ "                    \"phoneNo\": null,\n"
				+ "                    \"custmerId\": null,\n"
				+ "                    \"customerRelatedPartyBookingLocList\": [\n"
				+ "                        {\n"
				+ "                            \"bookingLocationId\": 1224\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"bookingLocationId\": 1218\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"relatedPartyFieldConfigFieldInfoList\": [\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1905,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1910,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1912,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10967,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10968,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10969,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10970,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1911,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10979,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1909,\n"
				+ "                            \"value\": 2254\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1908,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10983,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1916,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10980,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4289,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4677,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1918,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1919,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11022,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1923,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11023,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11027,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1927,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1928,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1926,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11078,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1933,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11052,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11079,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11080,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11081,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11082,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11083,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1935,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1936,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4215,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11084,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11085,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11086,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11087,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11088,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11089,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11090,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11136,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11137,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11138,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11139,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11140,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11141,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11148,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11195,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11196,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1939,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1940,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1941,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1942,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4217,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1944,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1945,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1946,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1947,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4162,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4163,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4170,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4815,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4816,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4817,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4818,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4819,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4820,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4821,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4822,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11065,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11066,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11067,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11068,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11069,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11070,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11071,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11072,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11073,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11074,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11075,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11076,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11077,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4823,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4824,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4825,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4826,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"relatedPartyDocConfigFieldInfoList\": [\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11180,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 2107,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11168,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11169,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11170,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11171,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11174,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11178,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 2083,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11175,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11176,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"documentId\": 11177,\n"
				+ "                            \"fieldList\": [\n"
				+ "                                4677\n"
				+ "                            ],\n"
				+ "                            \"documentInfo\": {\n"
				+ "                                \"path\": \"\",\n"
				+ "                                \"mimeType\": \"\",\n"
				+ "                                \"fileName\": \"\",\n"
				+ "                                \"dmsDocumentId\": \"\",\n"
				+ "                                \"fileExtension\": \"\"\n"
				+ "                            }\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"otherDocumentsList\": [],\n"
				+ "                    \"uniqueIdentifier\": \"7b1267f7-8de4-4f0d-b970-6bd61474a660\"\n"
				+ "                }\n"
				+ "            ]\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"customerSegId\": 1,\n"
				+ "    \"specialDDList\": []\n"
				+ "}";
		return body;
	}

	
	
	public String post_PublicBody(ScenarioContext scenarioContext) {

		String body = "{\n"
				+ "    \"tenantId\": 5,\n"
				+ "    \"customerName\": \""+customerName(scenarioContext)+"\",\n"
				+ "    \"riskRatingId\": 1998,\n"
				+ "    \"locale\": \"en\",\n"
				+ "    \"customerRelatedPartyMappingDTOList\": [\n"
				+ "        {\n"
				+ "            \"relatedPartyFieldDocumentMappingDTOList\": [\n"
				+ "                {\n"
				+ "                    \"id\": null,\n"
				+ "                    \"relatedPartyId\": 1810,\n"
				+ "                    \"designationId\": null,\n"
				+ "                    \"orgTypeId\": 163,\n"
				+ "                    \"coiNationalityId\": 109,\n"
				+ "                    \"name\": \""+customerName(scenarioContext)+"\",\n"
				+ "                    \"phoneNo\": null,\n"
				+ "                    \"custmerId\": null,\n"
				+ "                    \"customerRelatedPartyBookingLocList\": [\n"
				+ "                        {\n"
				+ "                            \"bookingLocationId\": 1229\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"relatedPartyFieldConfigFieldInfoList\": [\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1909,\n"
				+ "                            \"value\": 2253\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10983,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1916,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 10980,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4289,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4746,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1923,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11023,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11083,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1935,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 1936,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11089,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11090,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11136,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4823,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4824,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4825,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 4826,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11208,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        },\n"
				+ "                        {\n"
				+ "                            \"fieldId\": 11209,\n"
				+ "                            \"value\": \"\"\n"
				+ "                        }\n"
				+ "                    ],\n"
				+ "                    \"relatedPartyDocConfigFieldInfoList\": [],\n"
				+ "                    \"otherDocumentsList\": [],\n"
				+ "                    \"uniqueIdentifier\": \"cf939326-71c1-4c92-8673-85d82fcb7da3\"\n"
				+ "                }\n"
				+ "            ]\n"
				+ "        }\n"
				+ "    ],\n"
				+ "    \"customerSegId\": 1,\n"
				+ "    \"specialDDList\": []\n"
				+ "}";
		return body;
	}
}
